### PR TITLE
Upload master and develop branches as "versions" 

### PR DESCRIPTION
**Pull request by williln**
Part of #386 and #617 

- Adds a field `full_release` to the Version model to allow us to tell which versions aren't betas or full releases 
- Adds a task to add the `master` and `development` versions to the db 
- Minor refactoring to other tasks to add that task into other processes 
- Refactor the "most recent version" manager method to exclude non-releases (so `master` and `develop` are never pre-selected in the drop-down menu) 
- Hides the downloads table if there are no downloads 
- Adjusts the heading of the releases page to accommodate development branches 

**To add the master and develop branches to the database**, click the "Import New Releases" button in the admin. 

**Example of the default Releases page** -- see `develop` and `master` branches in the drop-down, but the most recent full version is pre-selected. 

Screenshot 2023-11-14 at 12 40 41 PM

**Example of the dev branch page**, with no downloads and no release date. 
Screenshot 2023-11-14 at 12 41 28 PM

### CODE REVIEW

**Comment by williln** [comment]
@frankwiles @4down Some things this PR does not cover: 

- [ ] Accessing downloads for the `master` and `develop` versions. For releases, we go to `https://boostorg.jfrog.io/artifactory/main/release/` and get the file from the right release, but `master` and `develop` aren't included. `https://boostorg.jfrog.io/artifactory/main/` shows `develop/` and `master/` directories. But their contents are still for more than one future release, and are named in the 1.84.0 style, so I'm not sure whether we want downloads or which ones to retrieve if we do. Here is a screenshot of what is available in the `develop` directory as an example: 

Screenshot 2023-11-14 at 12 45 11 PM

- [ ] Adding LibraryVersions. That will be another PR. 
- [ ] Adding the release notes to the Release Details page. I am still not sure where that data comes from so that will also be another PR.

**Comment by williln** [comment]
@sdarwin Can you tell me whether we want to include downloads for the `master` and `develop` branch releases? If so, which files should I be looking for? It looks like this is the contents of those files: https://github.com/cppalliance/temp-site/pull/827#issuecomment-1811251613

**Comment by sdarwin** [comment]
> whether we want to include downloads for the master and develop branch releases?

The main feature is to make the documentation accessible.    

I would tend to think that develop/master should not be shown at all on the Releases page https://www.preview.boost.org/releases/ .      They aren't releases.  

In Issue 386, Frank's latest comment was:

"""
UPDATED: Change of plan . We really would just want there to be a "Master" and "Develop" buttons next to the select box which would select those versions and leave the existing select box alone.
"""

That may still be open to interpretation.   But if they are included in the drop-down, what if the current version were emphasized such as "1.83.0 **(latest)**" .    Example:


Screenshot from 2023-11-14 18-31-13

**Comment by williln** [comment]
@sdarwin Based on your feedback, I am going to merge what is here (including the `master` and `develop` branches being in the drop-down) so that we have them, and if/when we get to the point of adding buttons, that's not hard to do -- it will involve adding a `{% url %}` tag to the template that points to the branch we want, and potentially removing them from the drop-down. 

I will not add the downloads from Artifactory for the `master` and `develop` branches since they are not releases. Thanks!

**Pull request merged**
